# Generated by Django 4.2.4 on 2023-12-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GruppoListino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gruppo', models.CharField(max_length=30)),
                ('descrizione_gruppo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Gruppo Listino',
                'verbose_name_plural': 'Gruppi Listino',
            },
        ),
        migrations.CreateModel(
            name='Programmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_programma', models.CharField(max_length=50)),
                ('descrizione_programma', models.CharField(max_length=250)),
                ('descrizione_in_fattura', models.CharField(max_length=250)),
                ('durata_programma', models.IntegerField(blank=True, null=True)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fasce_kg', models.CharField(blank=True, max_length=5, null=True)),
                ('validita_per_bilanciamento', models.BooleanField(default=False)),
                ('programma_attivo', models.BooleanField(default=False)),
                ('programma_intero', models.BooleanField(default=False)),
                ('programma_amministratore', models.BooleanField(default=False)),
                ('data_creazione', models.DateField(auto_now_add=True)),
                ('data_ultima_modifica', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programma',
                'verbose_name_plural': 'Programma',
            },
        ),
        migrations.CreateModel(
            name='TipoVoceListino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_voce_listino', models.CharField(max_length=30)),
                ('descrizione_voce_listino', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Tipo Voce Listino',
                'verbose_name_plural': 'Tipo Voci Listino',
            },
        ),
    ]
