# Generated by Django 4.2.4 on 2023-12-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accordi', '0001_initial'),
        ('amministrazione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmi',
            name='codiceiva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amministrazione.codiciiva'),
        ),
        migrations.AddField(
            model_name='programmi',
            name='gruppo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruppo', to='accordi.gruppolistino'),
        ),
    ]
