# Generated by Django 4.2.4 on 2023-12-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulenti', '0001_initial'),
        ('accordi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmi',
            name='listino_dedicato',
            field=models.ManyToManyField(blank=True, related_name='listino_dedicato', to='consulenti.struttura'),
        ),
        migrations.AddField(
            model_name='programmi',
            name='voce_listino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accordi.tipovocelistino'),
        ),
        migrations.AddField(
            model_name='gruppolistino',
            name='voce_listino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accordi.tipovocelistino'),
        ),
    ]
