# Generated by Django 4.2.4 on 2023-12-15 11:28

import amministrazione.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccordoNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_accordo', models.CharField(default=amministrazione.models.incremento_accordo, max_length=10)),
                ('tipo_accordo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Numero Accordo',
                'verbose_name_plural': 'Numeri Accordi',
            },
        ),
        migrations.CreateModel(
            name='AccordoNumeroCorner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_accordo', models.CharField(default=amministrazione.models.incremento_accordo_corner, max_length=10)),
                ('tipo_accordo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Numero Accordo Corner',
                'verbose_name_plural': 'Numeri Accordi Corner',
            },
        ),
        migrations.CreateModel(
            name='Alimenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('classe_alimenti', models.CharField(choices=[('Legumi', 'Legumi'), ('Latticini', 'Latticini'), ('Frutta secca', 'Frutta secca'), ('Uovo', 'Uovo'), ('Tacchino', 'Tacchino'), ('Manzo', 'Manzo'), ('Maiale', 'Maiale'), ('Coniglio', 'Coniglio'), ('Vitello', 'Vitello'), ('Agnello', 'Agnello'), ('Frutta', 'Frutta'), ('Verdura', 'Verdura'), ('Pesce', 'Pesce'), ('Pollo', 'Pollo'), ('Crostacei', 'Crostacei'), ('Molluschi', 'Molluschi')], max_length=25)),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimenti',
            },
        ),
        migrations.CreateModel(
            name='AnagraficaProvvigioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(blank=True, max_length=3, null=True)),
                ('importo_linea', models.CharField(blank=True, max_length=10, null=True)),
                ('percentuale', models.CharField(blank=True, max_length=3, null=True)),
                ('data_inizio_validita', models.DateTimeField(blank=True, null=True)),
                ('data_fine_validita', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Anagrafica Provvigione',
                'verbose_name_plural': 'Anagrafica Provvigioni',
            },
        ),
        migrations.CreateModel(
            name='CodiciIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=3)),
                ('valore', models.IntegerField()),
                ('descrizione', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Codice Iva',
                'verbose_name_plural': 'Codici Iva',
            },
        ),
        migrations.CreateModel(
            name='Costanti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=20)),
                ('descrizione', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Costante',
                'verbose_name_plural': 'Costanti',
            },
        ),
        migrations.CreateModel(
            name='DettaglioOrdini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiave_listino', models.CharField(max_length=5)),
                ('nome_listino', models.CharField(max_length=50)),
                ('descrizione_programma', models.CharField(max_length=250)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gratuita', models.BooleanField(default=False)),
                ('iva', models.IntegerField(blank=True, null=True)),
                ('imponibile', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Dettaglio Ordine',
                'verbose_name_plural': 'Dettaglio Ordini',
            },
        ),
        migrations.CreateModel(
            name='Documentazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(blank=True, max_length=60, null=True)),
                ('descrizione_documento', models.CharField(max_length=30)),
                ('percorso', models.CharField(max_length=100)),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
            },
        ),
        migrations.CreateModel(
            name='EmailAzienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('testo_oggetto', models.CharField(max_length=50)),
                ('testo_mail', models.TextField(blank=True, null=True)),
                ('bcc', models.EmailField(blank=True, max_length=150, null=True)),
                ('bcc2', models.EmailField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Email Azienda',
                'verbose_name_plural': 'Email Azienda',
            },
        ),
        migrations.CreateModel(
            name='FileCaricabili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodifile', models.CharField(max_length=20)),
                ('descrizione', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'File Caricabile',
                'verbose_name_plural': 'File Caricabili',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validita_per_bilanciamento', models.BooleanField(blank=True, default=False, null=True)),
                ('indirizzo', models.CharField(max_length=100)),
                ('numero_civico', models.CharField(max_length=5, null=True)),
                ('cap', models.CharField(max_length=5)),
                ('citta', models.CharField(max_length=25)),
                ('data_creazione', models.DateTimeField()),
                ('data_ultima_modifica', models.DateTimeField(blank=True, null=True)),
                ('data_pagamento_ordine', models.DateField(blank=True, null=True)),
                ('modalita_pagamento', models.CharField(choices=[('Integrale', 'Saldo Immediato'), ('Rateale', 'Pagamento Rateale'), ('Finanziato', 'Pagamento attraverso finanziaria')], max_length=50)),
                ('importo_acconto', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('numero_rate', models.IntegerField(blank=True, null=True)),
                ('mesi_tra_le_rate', models.IntegerField(blank=True, null=True)),
                ('importo_rata', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('stato_ordine', models.CharField(choices=[('Inserito', 'Inserito nel sistema'), ('Attesa', 'Attesa del Pagamento'), ('Attivato', 'Ordine in lavorazione'), ('Sospeso', 'Ordine Sospeso')], max_length=50)),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
            },
        ),
        migrations.CreateModel(
            name='Scadenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_scadenza', models.DateField()),
                ('data_pagamento_ordine', models.DateField(blank=True, null=True)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('stato_ordine', models.CharField(choices=[('Pagato', 'Pagamento Inserito'), ('Non Pagato', 'In Attesa del Pagamento')], max_length=20)),
            ],
            options={
                'verbose_name': 'Scadenza',
                'verbose_name_plural': 'Scadenze',
            },
        ),
    ]
