# Generated by Django 4.2.4 on 2023-12-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clienti', '0001_initial'),
        ('amministrazione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scadenze',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clienti.anagraficacliente'),
        ),
    ]
