# Generated by Django 4.2.4 on 2023-12-15 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accordi', '0003_initial'),
        ('consulenti', '0001_initial'),
        ('amministrazione', '0002_initial'),
        ('clienti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scadenze',
            name='consulente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consulenti.anagraficaconsulente'),
        ),
        migrations.AddField(
            model_name='scadenze',
            name='numero_ordine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amministrazione.accordonumero'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clienti.anagraficacliente'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='consulente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consulenti.anagraficaconsulente'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='numero_ordine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amministrazione.accordonumero'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='utente_inserimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordine',
            name='utente_ultima_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utente_modifica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filecaricabili',
            name='profiloutente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulenti.ruoliconsulente'),
        ),
        migrations.AddField(
            model_name='dettaglioordini',
            name='ordine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amministrazione.ordine'),
        ),
        migrations.AddField(
            model_name='anagraficaprovvigioni',
            name='consulente_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulenti.anagraficaconsulente'),
        ),
        migrations.AddField(
            model_name='anagraficaprovvigioni',
            name='listino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accordi.programmi'),
        ),
        migrations.AddField(
            model_name='anagraficaprovvigioni',
            name='rete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consulenti.struttura'),
        ),
        migrations.AddField(
            model_name='anagraficaprovvigioni',
            name='tipo_consulente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulenti.ruoliconsulente'),
        ),
    ]
