# Generated by Django 4.2.4 on 2023-12-15 11:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amministrazione', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnagraficaConsulente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('luogo_di_nascita', models.CharField(max_length=50)),
                ('provincia_di_nascita', models.CharField(max_length=2)),
                ('data_nascita', models.DateField()),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('indirizzo', models.CharField(max_length=100)),
                ('numero_civico', models.CharField(max_length=5, null=True)),
                ('cap', models.CharField(max_length=5)),
                ('citta_di_residenza', models.CharField(max_length=25)),
                ('provincia_di_residenza', models.CharField(max_length=2)),
                ('regione_residenza', models.CharField(max_length=30)),
                ('stato_residenza', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cellulare', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=150)),
                ('banca_appoggio', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('ruolo_altra_azienda', models.BooleanField(default=False)),
                ('imponibile_provvigionale', models.FloatField(blank=True, null=True)),
                ('imponibile_provvigionale_parole', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('partita_iva_ateco', models.BooleanField(default=False)),
                ('partita_iva', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('gestione_separata_inps', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modifica', models.DateTimeField(auto_now_add=True)),
                ('livello_consulente', models.IntegerField(choices=[(0, '-------'), (1, 'Manager'), (2, 'Top Manager'), (3, 'Silver Manager'), (4, 'Gold Manager'), (5, 'Platinum Manager')], default=0)),
                ('beauty_specialist', models.BooleanField(default=False)),
                ('data_tesserino', models.DateField(blank=True, null=True)),
                ('numero_tesserino', models.IntegerField(blank=True, null=True)),
                ('numero_IVD', models.IntegerField(blank=True, null=True)),
                ('id_superiore', models.ForeignKey(blank=True, null=True, on_delete=models.SET('senza superiore'), to='consulenti.anagraficaconsulente')),
            ],
            options={
                'verbose_name': 'Consulente',
                'verbose_name_plural': 'Consulenti',
            },
        ),
        migrations.CreateModel(
            name='FormulaCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('prezzo', models.CharField(max_length=10)),
                ('premio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RegimiFiscali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regime', models.CharField(max_length=20)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Regime Fiscale',
                'verbose_name_plural': 'Regimi Fiscali',
            },
        ),
        migrations.CreateModel(
            name='Struttura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Struttura Consulente',
            },
        ),
        migrations.CreateModel(
            name='RuoliConsulente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(blank=True, max_length=40, null=True)),
                ('proviggione_unica', models.BooleanField(default=True)),
                ('percorso', models.ManyToManyField(blank=True, null=True, to='consulenti.struttura')),
                ('visibile', models.ManyToManyField(default='Consulenti', to='auth.group')),
            ],
            options={
                'verbose_name': 'Ruolo Consulente',
                'verbose_name_plural': 'Ruoli Consulenti',
            },
        ),
        migrations.CreateModel(
            name='ProvvigioniConsulenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('data_inserimento_ordine', models.DateField()),
                ('data_pagamento_ordine', models.DateField()),
                ('ordine_rateale', models.BooleanField(default=False)),
                ('rata', models.CharField(blank=True, max_length=100, null=True)),
                ('provvigione_da_elaragire', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('consulente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulenti.anagraficaconsulente')),
                ('ordine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amministrazione.ordine')),
            ],
            options={
                'verbose_name': 'Provvigione Consulente',
                'verbose_name_plural': 'Provvigioni Consulenti',
            },
        ),
        migrations.CreateModel(
            name='NotuleConsulenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('dataemissione', models.DateField(default=datetime.date.today)),
                ('bloccata', models.BooleanField(default=False)),
                ('datariferimento', models.DateField(default=datetime.date.today)),
                ('consulente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulenti.anagraficaconsulente')),
            ],
            options={
                'verbose_name': 'Notula Consulente',
                'verbose_name_plural': 'Notule Consulenti',
            },
        ),
        migrations.CreateModel(
            name='FileCaricatiConsulente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percorso', models.CharField(max_length=100)),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('consulente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulenti.anagraficaconsulente')),
                ('tipo_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amministrazione.filecaricabili')),
            ],
            options={
                'verbose_name': 'File Caricato',
                'verbose_name_plural': 'File Caricati',
            },
        ),
        migrations.CreateModel(
            name='DatiAggiuntiviPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=10)),
                ('percentuale', models.BooleanField(default=False)),
                ('rete', models.CharField(max_length=50)),
                ('stato', models.BooleanField(default=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica_stato', models.DateTimeField(blank=True, null=True)),
                ('consulente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consulente', to='consulenti.anagraficaconsulente')),
            ],
            options={
                'verbose_name': 'Dati Aggiuntivi Partner',
                'verbose_name_plural': 'Dati Aggiuntivi Partner',
            },
        ),
        migrations.CreateModel(
            name='DatiAggiuntiviCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corner', models.BooleanField(choices=[(True, 'Corner'), (False, 'Centro Autorizzato')], default=False)),
                ('titolare_di', models.IntegerField(choices=[(1, 'Centro Benessere/Estetico'), (2, 'Palestra/Personal Trainer'), (3, 'Studio Specialista')], default=1)),
                ('denominato', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=10)),
                ('comune', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=10)),
                ('PICF', models.CharField(max_length=50)),
                ('pagamento', models.BooleanField(choices=[(True, 'Unica Soluzione'), (False, 'Rateizzato')], default=False)),
                ('affiliatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliatore', to='consulenti.anagraficaconsulente')),
                ('consulente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corner', to='consulenti.anagraficaconsulente')),
                ('formula_scelta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulenti.formulacentro')),
                ('numero_accordo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='amministrazione.accordonumerocorner')),
                ('seguito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguito', to='consulenti.anagraficaconsulente')),
            ],
        ),
        migrations.AddField(
            model_name='anagraficaconsulente',
            name='regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulenti.regimifiscali'),
        ),
        migrations.AddField(
            model_name='anagraficaconsulente',
            name='tipo_consulente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulenti.ruoliconsulente'),
        ),
        migrations.AddField(
            model_name='anagraficaconsulente',
            name='tipo_struttura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulenti.struttura'),
        ),
        migrations.AddField(
            model_name='anagraficaconsulente',
            name='utente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utente', to=settings.AUTH_USER_MODEL),
        ),
    ]
