# Generated by Django 4.2.2 on 2023-08-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatologieClienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('patologia_sesso', models.CharField(choices=[('T', 'Tutti'), ('U', 'Uomo'), ('D', 'Donna')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('citta_nascita', models.CharField(max_length=25)),
                ('data_nascita', models.DateField()),
                ('indirizzo', models.CharField(max_length=100)),
                ('numero_civico', models.CharField(max_length=10, null=True)),
                ('cap', models.CharField(max_length=5)),
                ('citta', models.CharField(max_length=25)),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cellulare', models.CharField(max_length=15)),
                ('altezza', models.CharField(blank=True, max_length=7, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('sesso', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('privacy', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modifica', models.DateTimeField(auto_now_add=True)),
                ('ragione_sociale', models.CharField(blank=True, max_length=100, null=True)),
                ('sede', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('indirizzo_sede', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cap_sede', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('telefono_sede', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('email_sede', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('partita_iva', models.CharField(blank=True, max_length=11, null=True)),
                ('codice_univoco', models.CharField(blank=True, max_length=8, null=True)),
                ('beneficiario_nome', models.CharField(blank=True, max_length=50, null=True)),
                ('beneficiario_cognome', models.CharField(blank=True, max_length=50, null=True)),
                ('beneficiario_cellulare', models.CharField(blank=True, max_length=15, null=True)),
                ('beneficiario_codice_fiscale', models.CharField(blank=True, max_length=16, null=True)),
                ('consulente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utente.anagrafica')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
    ]
