# Generated by Django 4.2.4 on 2023-08-22 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clienti', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anagrafica',
            new_name='AnagraficaUtente',
        ),
    ]
